version: '3.8'

services:
  auth:
    restart: always
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: ghcr.io/swde78/weather-app-pipeline:latest
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - app-net

  ui:
    restart: always
    build:
      context: ./UI
      dockerfile: Dockerfile
    image: ghcr.io/swde78/weather-app-pipeline:latest
    depends_on:
      - auth
      - weather
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
    ports:
      - "3000:3000"
    networks:
      - app-net
  weather:
    restart: always
    build:
      context: ./weather
      dockerfile: Dockerfile
    image: ghcr.io/swde78/weather-app-pipeline:latest
    environment:
      APIKEY: ${APIKEY}
    networks:
      - app-net
  db:
    restart: always
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - app-net
    volumes:
      - ./db-data:/var/lib/mysql
networks:
  app-net:
    driver: bridge
volumes:
  db-data:


