name: Weather-image Pipeline
on:
  push:
    branches:
      - main:

jobs:
  build:
    runs-on: ubuntu-latest


    services:
      db:    
        image: mysql:8.0.25
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        volumes:
          - db-data:/var/lib/mysql


    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Build and push auth service
        uses: docker/build-push-action@v5
        with:
          context: ./auth
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/weather-app:latest
            ghcr.io/${{ github.repository_owner }}/weather-app:${{ github.sha }}


       
      - name: Build and push UI service
         uses: docker/build-push-action@v5
         with:
           context: ./UI
           push: true
           tags: |
             ghcr.io/${{ github.repository_owner }}/weather-app:latest
             ghcr.io/${{ github.repository_owner }}/weather-app:${{ github.sha }}


                   
      - name: Build and push weather service
        uses: docker/build-push-action@v5
        with:
          context: ./weather
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/weather-app:latest
            ghcr.io/${{ github.repository_owner }}/weather-app:${{ github.sha }}

